phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run generate
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id EHATL4FKZLJIZ --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'